baseURL = "https://pedronofuentes.github.io/"
languageCode = "en-us"
title = "Pedro Nofuentes"
theme = "hermit"
enableEmoji = true

[params]
  homeSubtitle = "Software engineer, playing between code and containers"

  [[params.social]]
    name = "github"
    url = "https://github.com/pedronofuentes"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/pedronofuentes"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/pedronofuentesazcarate"
